### ISSUE TITLE
Improvement in code and joining community

### ISSUE THREAD

**Issue by Rahulbaran** [lellowgill/Stop_Watch_project#9]
### 👋 Deborah, I am Rahul from India.

I went through your code and have shared some points which you may consider to improve your code:-
1. You should use `rem`/ `em` as unit instead of `px`
2. Use **CSS Variables (Custom Properties)** to make your code *DRY(Don't Repeat Yourself )*. 
3. Use `const` instead of `let` for those variables which you are not going to reassign and it will help to avoid some bugs. 
    **For example :-** Suppose you have a variable which you don't want to reassign then use `const` & if you try to reassign its value anywhere in your code then it will throw an error. but if you will use `let` and mistakenly you reassign it then it will occur without throwing any error, which might cause bugs in your code 
   ```
   const name = 'Deborah';
   ```

I have shared some resources here which will be beneficial for you to understand above concepts , I have mentioned
* [CSS Variables by MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/--*), [CSS Variables by Google](https://developers.google.com/web/updates/2016/02/css-variables-why-should-you-care)
* [CSS Units MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units), [em vs rem by css-tricks](https://css-tricks.com/confused-rem-em/)
* [var, let & const](https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/#:~:text=var%20variables%20can%20be%20updated,const%20variables%20are%20not%20initialized.)

You should also join some discord servers, twitter, reddit, youtube channles and other social platforms. I have shared some discord servers link here which might be helpful:-
1. [Server by Kevin Powell](https://discord.gg/pVSzs8b6)
2. [EddieHub](https://discord.gg/XbUuQDzw)

One last tip, use google for anything topic where you have stuck , there are unlimited free resources out there.

Thank you🙂, Merry Christmas 🎄

**Comment by lellowgill** [comment]
Happy morning,

Thank you so much for this feedback. I am grateful to have you around to check my code.

**Comment by lellowgill** [comment]
Happy Christmas to you!

**Comment by Rahulbaran** [comment]
Good Evening from India
I am very glad that I could help🙂. Btw, Checkout [FrontendMentor](https://www.frontendmentor.io/), there are some great projects to practice & to sharp your knowledge.

Be consistent with your coding habit and you will have a great future🙂😇

**Comment by Rahulbaran** [comment]
Now, I am closing this, If you need some help then you can open it.
